"""add foreign keys to all models

Revision ID: 57d65a53273a
Revises: b38dc4f49200
Create Date: 2026-04-17 09:41:24.483289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d65a53273a'
down_revision: Union[str, None] = 'b38dc4f49200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'badges', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'disputes', 'users', ['filed_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'disputes', 'reviews', ['review_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'reviews', 'profiles', ['target_profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'users', ['reviewer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tag_aggregations', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag_aggregations', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'disputes', type_='foreignkey')
    op.drop_constraint(None, 'disputes', type_='foreignkey')
    op.drop_constraint(None, 'badges', type_='foreignkey')
    # ### end Alembic commands ###
