"""initial tables

Revision ID: b38dc4f49200
Revises: 
Create Date: 2026-04-17 09:29:49.401747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b38dc4f49200'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_events_created_at'), 'activity_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_events_event_name'), 'activity_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_activity_events_session_id'), 'activity_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_activity_events_user_id'), 'activity_events', ['user_id'], unique=False)
    op.create_table('badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('badge_type', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badges_badge_type'), 'badges', ['badge_type'], unique=False)
    op.create_index(op.f('ix_badges_profile_id'), 'badges', ['profile_id'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('filed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('counter_evidence_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('open', 'investigating', 'resolved_in_favor', 'resolved_rejected', name='dispute_status'), nullable=False),
    sa.Column('resolved_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_filed_by_user_id'), 'disputes', ['filed_by_user_id'], unique=False)
    op.create_index(op.f('ix_disputes_review_id'), 'disputes', ['review_id'], unique=True)
    op.create_index(op.f('ix_disputes_status'), 'disputes', ['status'], unique=False)
    op.create_table('fraud_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='fraud_severity'), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('target_profile_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('auto_actions_taken', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('open', 'investigating', 'resolved', 'false_positive', name='fraud_alert_status'), nullable=False),
    sa.Column('resolved_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_alerts_created_at'), 'fraud_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_rule_name'), 'fraud_alerts', ['rule_name'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_severity'), 'fraud_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_status'), 'fraud_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_target_user_id'), 'fraud_alerts', ['target_user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('review_received', 'dispute_window_expiring', 'dispute_filed', 'dispute_resolved', 'review_verified', 'review_rejected', 'profile_claimed', 'score_updated', 'badge_earned', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('handle', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('profile_type', sa.Enum('creator', 'agency', 'brand', name='profile_type'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('youtube_channel_id', sa.String(length=255), nullable=True),
    sa.Column('instagram_handle', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('social_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_claimed', sa.Boolean(), nullable=False),
    sa.Column('is_dummy', sa.Boolean(), nullable=False),
    sa.Column('is_opted_out', sa.Boolean(), nullable=False),
    sa.Column('access_level', sa.Enum('full', 'limited', name='access_level'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_category'), 'profiles', ['category'], unique=False)
    op.create_index(op.f('ix_profiles_handle'), 'profiles', ['handle'], unique=True)
    op.create_index(op.f('ix_profiles_profile_type'), 'profiles', ['profile_type'], unique=False)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('target_profile_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('brand_worked_with_creator', 'agency_worked_with_creator', 'creator_worked_with_brand', 'creator_worked_with_agency', name='relationship_type'), nullable=False),
    sa.Column('payment_status', sa.Enum('paid_on_time', 'paid_late', 'partially_paid', 'unpaid', name='payment_status'), nullable=False),
    sa.Column('rating_communication', sa.Integer(), nullable=False),
    sa.Column('rating_professionalism', sa.Integer(), nullable=False),
    sa.Column('rating_quality', sa.Integer(), nullable=False),
    sa.Column('rating_reliability', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ocr_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_dispute_window', 'disputed', 'pending_verification', 'verified', 'rejected', 'quarantined', name='review_status'), nullable=False),
    sa.Column('verified_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispute_window_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_reviews_status'), 'reviews', ['status'], unique=False)
    op.create_index(op.f('ix_reviews_target_profile_id'), 'reviews', ['target_profile_id'], unique=False)
    op.create_table('tag_aggregations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_aggregations_profile_id'), 'tag_aggregations', ['profile_id'], unique=False)
    op.create_index(op.f('ix_tag_aggregations_tag'), 'tag_aggregations', ['tag'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('creator', 'agency', 'brand', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('linkedin_id', sa.String(length=255), nullable=True),
    sa.Column('instagram_id', sa.String(length=255), nullable=True),
    sa.Column('phone_encrypted', sa.Text(), nullable=True),
    sa.Column('trust_weight', sa.Float(), nullable=False),
    sa.Column('subscription_tier', sa.Enum('free', 'premium', name='subscription_tier'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('instagram_id'),
    sa.UniqueConstraint('linkedin_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tag_aggregations_tag'), table_name='tag_aggregations')
    op.drop_index(op.f('ix_tag_aggregations_profile_id'), table_name='tag_aggregations')
    op.drop_table('tag_aggregations')
    op.drop_index(op.f('ix_reviews_target_profile_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_status'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_profile_type'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_handle'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_category'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_fraud_alerts_target_user_id'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_status'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_severity'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_rule_name'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_created_at'), table_name='fraud_alerts')
    op.drop_table('fraud_alerts')
    op.drop_index(op.f('ix_disputes_status'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_review_id'), table_name='disputes')
    op.drop_index(op.f('ix_disputes_filed_by_user_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_badges_profile_id'), table_name='badges')
    op.drop_index(op.f('ix_badges_badge_type'), table_name='badges')
    op.drop_table('badges')
    op.drop_index(op.f('ix_activity_events_user_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_session_id'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_event_name'), table_name='activity_events')
    op.drop_index(op.f('ix_activity_events_created_at'), table_name='activity_events')
    op.drop_table('activity_events')
    # ### end Alembic commands ###
